### PR TITLE
chore: bump cocoapods

### PR DESCRIPTION
**Pull request by alexandrius**

### CODE REVIEW

**Review by gutenye — APPROVED** [review]
utACK

**Comment by gutenye** [comment]
@alexandrius installed failed

```
==> Applying 2af8ba7e3477296d975243eeb1c12f379ab556a1.patch
patching file 'lib/cocoapods/target/build_settings.rb'
1 out of 1 hunks failed--saving rejects to 'lib/cocoapods/target/build_settings.rb.rej'

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/exodusmovement/homebrew-alt/issues
```

**Comment by alexandrius** [comment]
@gutenye I guess we no longer need [the patch](https://github.com/ExodusMovement/homebrew-alt/blob/aaa160fbe4cc2fa866171f07af9fd8f8acb128c9/Formula/cocoapods.rb#L19-L30). What do you think?

**Comment by gutenye** [comment]
Yes, and we can copy it from [here](https://github.com/Homebrew/homebrew-core/blob/master/Formula/cocoapods.rb)

**Pull request merged**
