### PR TITLE
refactor: remove cocoapods ruby patch

### PR DESCRIPTION
**Pull request by alexandrius**
Installation went through this time.

```
brew install Formula/cocoapods.rb 
Running `brew update --auto-update`...
==> Auto-updated Homebrew!
==> Updated Homebrew from f7b322557 to 4.0.19 (33ab8e755).
Updated 2 taps (homebrew/core and homebrew/cask).
==> New Formulae
ast-grep           clive              libmediainfo       mods               rojo               yamlfmt
boolector          libabigail         libzen             roblox-ts          rye
==> New Casks
smooze-pro

You have 28 outdated formulae installed.


The 4.0.0 release notes are available on the Homebrew Blog:
  https://brew.sh/blog/4.0.0
The 4.0.19 changelog can be found at:
  https://github.com/Homebrew/brew/releases/tag/4.0.19
Error: Failed to load cask: Formula/cocoapods.rb
Cask 'cocoapods' is unreadable: wrong constant name #<Class:0x0000000138619f70>
Warning: Treating Formula/cocoapods.rb as a formula.
cocoapods 1.12.1 is already installed but outdated (so it will be upgraded).
==> Fetching cocoapods
==> Downloading https://github.com/CocoaPods/CocoaPods/archive/1.12.1.tar.gz
==> Downloading from https://codeload.github.com/CocoaPods/CocoaPods/tar.gz/refs/tags/1.12.1
##  #                                                                                      -=O=-                  
==> Upgrading cocoapods
  1.12.1 -> 1.12.1_2 

==> gem build cocoapods.gemspec
==> gem install cocoapods-1.12.1.gem
🍺  /opt/homebrew/Cellar/cocoapods/1.12.1_2: 13,431 files, 27.8MB, built in 42 seconds
==> Running `brew cleanup cocoapods`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
Removing: /opt/homebrew/Cellar/cocoapods/1.12.1... (13,430 files, 27.8MB)
```

### CODE REVIEW

**Comment by gutenye** [comment]
Can you copy it from [here](https://github.com/Homebrew/homebrew-core/blob/master/Formula/cocoapods.rb), includes `bottle` and remove `revision`

**Comment by alexandrius** [comment]
@gutenye Done. I deliberately didn't copy full file I thought you had a modified version.

**Comment by gutenye** [comment]
Oh, I don't have a modified version, I just copied the old version here as that version is used by mobile

**Review by gutenye — APPROVED** [review]
utACK

**Pull request merged**
